config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :transports
  resources :users
  resources :test

  # get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :transport

  validates :time, presence: true
end

app/models/transport.rb
class Transport < ApplicationRecord
  has_many :reservations
  has_many :users, through: :reservations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :transports, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]



  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
    @users = User.all
    @transports = Transport.all


    @time_intervals = %w[
      00:00-01:00
      01:00-02:00
      02:00-03:00
      03:00-04:00
      04:00-05:00
      05:00-06:00
      06:00-07:00
      07:00-08:00
      08:00-09:00
      09:00-10:00
      10:00-11:00
      11:00-12:00
      12:00-13:00
      13:00-14:00
      14:00-15:00
      15:00-16:00
      16:00-17:00
      17:00-18:00
      18:00-19:00
      19:00-20:00
      20:00-21:00
      21:00-22:00
      22:00-23:00
      23:00-00:00
    ]

    end

  def get_value
    puts "hello"
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation  }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end


  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
      # @users = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :transport_id, :time)
      # params.require(:user).permit(:name, :user_id)
    end


end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :set_transport, only: %i[ show edit update destroy ]

  # GET /transports or /transports.json
  def index
    @transports = Transport.all
  end

  # GET /transports/1 or /transports/1.json
  def show
  end

  # GET /transports/new
  def new
    @transport = Transport.new
  end

  # GET /transports/1/edit
  def edit
  end

  # POST /transports or /transports.json
  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html { redirect_to transport_url(@transport), notice: "Transport was successfully created." }
        format.json { render :show, status: :created, location: @transport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transports/1 or /transports/1.json
  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to transport_url(@transport), notice: "Transport was successfully updated." }
        format.json { render :show, status: :ok, location: @transport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transports/1 or /transports/1.json
  def destroy
    @transport.destroy

    respond_to do |format|
      format.html { redirect_to transports_url, notice: "Transport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport
      @transport = Transport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transport_params
      params.require(:transport).permit(:name, :transport_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]



  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "AutenticReservation", root_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Mājās lapa", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rezervēt", new_reservation_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rezervācijas Tabula", reservations_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="card container">
  <h2 class="card-header">Reservation App</h2>
  <div class="card-body">
    <h5 class="card-title">In this App you can reserve transport!</h5>
    <p class="card-text">Creating this application I learned a lot about Ruby On Rails</p>
    <p class="card-text">And I certainly enjoyed it.</p>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AutenticReservation</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render "home/header" %>
<div class="px-5">
  <br/>
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% users = User.all %>
  <% user_arr = users.as_json.map { |user| [user.to_h['name'], user.to_h['user_id']] } %>

  <% transports = Transport.all %>
  <% transport_arr = transports.as_json.map { |transport| [transport.to_h['name'], transport.to_h['transport_id']] }
     time_intervals = %w[
      00:00-01:00
      01:00-02:00
      02:00-03:00
      03:00-04:00
      04:00-05:00
      05:00-06:00
      06:00-07:00
      07:00-08:00
      08:00-09:00
      09:00-10:00
      10:00-11:00
      11:00-12:00
      12:00-13:00
      13:00-14:00
      14:00-15:00
      15:00-16:00
      16:00-17:00
      17:00-18:00
      18:00-19:00
      19:00-20:00
      20:00-21:00
      21:00-22:00
      22:00-23:00
      23:00-00:00
    ]

  %>



  <div class="card " style="width: 40rem;">

    <div class="dropdown container">
      <%= form.label :user_id,"Lietotajs", style: "display: block" %>
      <%= form.select :user_id, user_arr, class: "btn btn-secondary dropdown-toggle" %>
    </div>

    <div class="dropdown container">
      <%= form.label :transport_id,"Transports", style: "display: block" %>
      <%= form.select :transport_id, transport_arr, class: "btn" %>
    </div>

    <p class="container">Laiks</p>

    <div class="card-body" style="display: flex; justify-content: space-around; align-items: center; flex-wrap: wrap; gap: 5px;">
      <% time_intervals.each do |interval| %>

        <div class="badge text-bg-secondary  border border-dark">
          <%= form.label :time, interval, style: "display: block" %>

          <%= form.radio_button :time, interval, class: 'form-check-input ', style: 'width:20px; height:20px; ' %>
        </div>

      <% end %>

    </div>
  </div>

  <br>

  <div>
    <%= form.submit "Uztaisīt rezervāciju" %>
  </div>
  <script>
      const transportDropdown = document.getElementById("reservation_transport_id");

      transportDropdown.addEventListener("click", () => {
          const transport_id = transportDropdown.options[transportDropdown.selectedIndex].value;
          <%
          reservations = Reservation.all.as_json

          taken_reservations = reservations.map { |reservation| [reservation.to_h['transport_id'], reservation.to_h['time']]}
          %>
          const taken_reservations = <%= raw taken_reservations %>

              taken_reservations.forEach((reservation) => {
                  if (transport_id == reservation[0]) {
                      options = document.getElementsByName('reservation[time]');
                      options.forEach((option) => {
                          option.disabled = option.value == reservation[1];
                      })
                  }
              })
      })

  </script>

<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p>
    <strong>User:</strong>
    <%= reservation.user_id %>
  </p>

  <p>
    <strong>Transport:</strong>
    <%= reservation.transport_id %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= reservation.time %>
  </p>

</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rezervācijas</h1>

<div id="reservations">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>X</th>
      <% @time_intervals.each do |interval| %>
        <th> <%= interval %></th>
      <% end %>
    </tr>
    </thead>

    <tbody>
    <% @transports.each do |transport| %>
      <tr>
        <td>
          <%= transport.name %>
        </td>
        <% @time_intervals.each do |interval| %>
          <td>
            <% transport.reservations.each do |reservation| %>
              <% if reservation.time == interval %>
                <%= button_to reservation.user.name, reservation, method: :delete, class: "btn btn-outline-danger" %>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>




<%= link_to "Jauna rezervācija", new_reservation_path %>

<!--  <td>-->

<!--        </td>
<%# user.reservations.each do |reservation| %>
<%#= reservation.transport.as_json.to_h["name"] %>
<%# end %>

app/views/reservations/new.html.erb
<div class="container"><h1 class="mx-auto">Rezervēt</h1>
<div class="mx-auto ">
<%= render "form", reservation: @reservation, users: @users %>
</div>
<br>

<div>

  <%= link_to "Atpakaļ pie rezervācijam", reservations_path %>
</div>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><b>Lietotajs</b> : <%= @reservation.user.name %></li>
    <li class="list-group-item"><b>Transports</b> : <%= @reservation.transport.name %></li>
    <li class="list-group-item"><b>Laiks</b> : <%= @reservation.time %></li>
  </ul>
</div>
<br/>

<div>
  <%= link_to "Izlabot rezervāciju", edit_reservation_path(@reservation) %> |
  <%= link_to "Atpakaļ pie rezervācijam", reservations_path %>

  <%= button_to "Izdzēst šo rezervāciju", @reservation, method: :delete %>
</div>

app/views/transports/_form.html.erb
<%= form_with(model: transport) do |form| %>
  <% if transport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transport.errors.count, "error") %> prohibited this transport from being saved:</h2>

      <ul>
        <% transport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :transport_id, style: "display: block" %>
    <%= form.number_field :transport_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transports/_transport.html.erb
<div id="<%= dom_id transport %>">
  <p>
    <strong>Name:</strong>
    <%= transport.name %>
  </p>

  <p>
    <strong>Transport:</strong>
    <%= transport.transport_id %>
  </p>

</div>

app/views/transports/edit.html.erb
<h1>Editing transport</h1>

<%= render "form", transport: @transport %>

<br>

<div>
  <%= link_to "Show this transport", @transport %> |
  <%= link_to "Back to transports", transports_path %>
</div>

app/views/transports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transports</h1>

<div id="transports">
  <% @transports.each do |transport| %>
    <%= render transport %>
    <p>
      <%= link_to "Show this transport", transport %>
    </p>
  <% end %>
</div>

<%= link_to "New transport", new_transport_path %>

app/views/transports/new.html.erb
<h1>New transport</h1>

<%= render "form", transport: @transport %>

<br>

<div>
  <%= link_to "Back to transports", transports_path %>
</div>

app/views/transports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transport %>

<div>
  <%= link_to "Edit this transport", edit_transport_path(@transport) %> |
  <%= link_to "Back to transports", transports_path %>

  <%= button_to "Destroy this transport", @transport, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user.user_id %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>